## Reading Image

In [4]:
import cv2
import numpy as np

In [2]:
image = cv2.imread("Cat.jpg")
print(image) # This is Numpy Arrays

[[[179 208 217]
  [178 207 216]
  [176 207 216]
  ...
  [210 222 232]
  [210 222 232]
  [209 221 231]]

 [[179 208 217]
  [178 207 216]
  [176 207 216]
  ...
  [210 222 232]
  [210 222 232]
  [210 222 232]]

 [[179 208 217]
  [178 207 216]
  [175 206 215]
  ...
  [210 222 232]
  [210 222 232]
  [210 222 234]]

 ...

 [[118 152 182]
  [119 153 183]
  [121 155 185]
  ...
  [197 213 225]
  [197 213 225]
  [197 213 225]]

 [[117 151 181]
  [118 152 182]
  [120 154 184]
  ...
  [197 213 225]
  [197 213 225]
  [196 212 224]]

 [[116 150 180]
  [117 151 181]
  [119 153 183]
  ...
  [197 213 225]
  [197 213 225]
  [198 214 226]]]


## Showing Image

In [ ]:
cv2.imshow("cat", image)
cv2.waitKey(0)

2025-01-13 15:53:24.201 Python[70674:8624847] +[IMKClient subclass]: chose IMKClient_Modern
2025-01-13 15:53:24.201 Python[70674:8624847] +[IMKInputSession subclass]: chose IMKInputSession_Modern


-1

In [6]:
# (height, width, channels)
image.shape

(1024, 1025, 3)

#### Channels = BRG (0, 1, 2)

In [7]:
# ':' means all of the rows or columns
image[:, :, 1] 

array([[208, 207, 207, ..., 222, 222, 221],
       [208, 207, 207, ..., 222, 222, 222],
       [208, 207, 206, ..., 222, 222, 222],
       ...,
       [152, 153, 155, ..., 213, 213, 213],
       [151, 152, 154, ..., 213, 213, 212],
       [150, 151, 153, ..., 213, 213, 214]],
      shape=(1024, 1025), dtype=uint8)

In [8]:
green_image = image[:, :, 1]

In [ ]:
cv2.imshow('green image', green_image)
cv2.waitKey(0)

2025-01-13 16:23:31.451 Python[70674:8624847] _TIPropertyValueIsValid called with 16 on nil context!
2025-01-13 16:23:31.451 Python[70674:8624847] imkxpc_getApplicationProperty:reply: called with incorrect property value 16, bailing.
2025-01-13 16:23:31.451 Python[70674:8624847] Text input context does not respond to _valueForTIProperty:


-1

## Saving Image

In [11]:
cv2.imwrite("Cat_green.jpg", green_image)

True

## Closing Window

In [21]:
cv2.destroyWindow("green image")

In [17]:
cv2.destroyAllWindows()

## Numpy Arrays
- Core data structure for images in OpenCV
- Represent images as multi-dimensional arrays:
- Grayscale: 2D (Height * Width)
- Colour: 3D (Height * Width * Channels)

In [27]:
image[60, 70]

array([222, 238, 244], dtype=uint8)

In [29]:
image[60, 70, 0]

np.uint8(222)

In [33]:
print(image.shape)
image[10:500, 50:600, :] = 0  # zero stands for black colour

(1024, 1025, 3)


In [34]:
image[60, 70, 0]

np.uint8(0)

In [36]:
cv2.imshow('framename', image)
cv2.waitKey(0)

-1

## Exercise

In [38]:
# read image
image = cv2.imread("Cat.jpg")

# ROI(Region of Interest) definition [y1:y2, x1:x2]
roi = image[50:150, 100:200]  # slicing

# paste ROI to another location
image[200:300, 300:400] = roi

# show the result
cv2.imshow("Modified Image", image)
cv2.waitKey(0)
# cv2.destroyAllWindows()

79

: 